# LC-AI-K210-7Mic on AX7Z020 J20, as wired for this bring-up.
set_property PACKAGE_PIN R14 [get_ports mic_d0_0]
set_property PACKAGE_PIN P14 [get_ports mic_d1_0]
set_property PACKAGE_PIN U12 [get_ports mic_d2_0]
set_property PACKAGE_PIN T12 [get_ports mic_d3_0]
set_property PACKAGE_PIN T15 [get_ports mic_ws_0]
set_property PACKAGE_PIN T14 [get_ports mic_bck_0]
set_property IOSTANDARD LVCMOS33 [get_ports {mic_d0_0 mic_d1_0 mic_d2_0 mic_d3_0 mic_ws_0 mic_bck_0}]
set_property SLEW SLOW [get_ports {mic_ws_0 mic_bck_0}]
set_property DRIVE 8 [get_ports {mic_ws_0 mic_bck_0}]

# FCLK0 is generated by PS7; the actual 50 MHz period is inherited from the
# validated AX7Z020 PS7 preset and is recorded in the physical evidence.
set_input_delay -clock [get_clocks -quiet FCLK_CLK0] -min 2.0 [get_ports {mic_d0_0 mic_d1_0 mic_d2_0 mic_d3_0}]
set_input_delay -clock [get_clocks -quiet FCLK_CLK0] -max 8.0 [get_ports {mic_d0_0 mic_d1_0 mic_d2_0 mic_d3_0}]
